# build as vortexing/gatk-bwa:4.2.20-0.7.17
FROM broadinstitute/gatk:4.2.2.0

RUN apt-get install -y zlib1g-dev
WORKDIR /
RUN curl -LO https://github.com/lh3/bwa/archive/v0.7.17.tar.gz
RUN tar zxf v0.7.17.tar.gz
WORKDIR /bwa-0.7.17
RUN make && cp ./bwa /usr/local/bin
WORKDIR /
RUN rm -rf v0.7.17.tar.gz bwa-0.7.17


