# build as ../griffin:v0.2.0
FROM python:3.7.4
RUN apt-get update --fix-missing -y

RUN apt-get install -y libz-dev libbz2-dev liblzma-dev make wget libncurses5-dev
RUN wget https://github.com/samtools/samtools/releases/download/1.14/samtools-1.14.tar.bz2 && \
    tar jxf samtools-1.14.tar.bz2 && \
    cd samtools-1.14 && ./configure && make install
## just bedtools
RUN apt-get install -y bedtools
###
RUN pip3 install numpy==1.17.3 cython==0.29.33
RUN pip3 install pysam==0.15.4 pyBigWig==0.3.17 pandas==1.2.4
RUN pip3 install scipy==1.7.1 matplotlib==3.4.1 pyyaml==5.3.1 argparse==1.1
RUN pip3 install pybedtools==0.8.0
RUN pip3 install statsmodels==0.10.1
### Griffin specific due to it being a private repo for now - replace later with git clone or wget of the zip
RUN wget https://github.com/GavinHaLab/Griffin/archive/refs/tags/v0.2.0.zip && unzip v0.2.0.zip && mv Griffin-0.2.0/ Griffin/


# Override the R CMD for workflow managers
CMD ["/bin/bash"]

