# build as ../ichorcna:v0.4.9
FROM rocker/r-base:4.1.2

RUN apt-get update --fix-missing -y

RUN apt-get install -y cmake
RUN apt-get install -y libcurl4-openssl-dev libssl-dev

## because there is no release to tether to, pick today's most recent commit.  Done 1/31/2022
RUN wget https://github.com/shahcompbio/hmmcopy_utils/archive/29a8d1d.zip && unzip 29a8d1d.zip 
RUN cmake ./hmmcopy_utils-29a8d1d18dfd301600d5d91832e5fe231935058c && make

## BioC packages
RUN R -e "install.packages('BiocManager',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "BiocManager::install('HMMcopy', ask = F)"
RUN R -e "BiocManager::install('GenomicRanges', ask = F)"
RUN R -e "BiocManager::install('GenomeInfoDb', ask = F)"
RUN apt-get install -y libxml2-dev
RUN R -e "BiocManager::install('BSgenome.Hsapiens.UCSC.hg19', ask = F)"
RUN R -e "BiocManager::install('BSgenome.Hsapiens.UCSC.hg38', ask = F)"
## CRAN packages
RUN R -e "install.packages(c('foreach', 'data.table','doMC', 'ggplot2', 'strings'),dependencies=TRUE, repos='http://cran.rstudio.com/')"

RUN wget https://github.com/vortexing/ichorCNA/archive/refs/tags/v0.4.9.zip && unzip v0.4.9.zip && mv ichorCNA-0.4.9/ ichorCNA/
RUN R -e "install.packages('./ichorCNA', repos = NULL, type = 'source')"


# Override the R CMD for workflow managers
CMD ["/bin/bash"]
